plugins:
  - babel
  - react

env:
  node: true
  browser: true

parser:
  babel-eslint

extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:react/recommended'

rules:
  react/prop-types: 0
